export default {
  FIREBASE_INIT: 'FIREBASE_INIT',
  PAUSE: 'PAUSE',
  PLAY_URL: 'PLAY_URL',
  SET_CONNECTION: 'SET_CONNECTION',
  SET_CURRENT_TAB: 'SET_CURRENT_TAB',
  SET_FOREGROUND: 'SET_FOREGROUND',
  SET_LANGUAGE: 'SET_LANGUAGE',
  SET_LAST_MESSAGE_ID: 'SET_LAST_MESSAGE_ID',
  SET_PLAYER: 'SET_PLAYER',
  SET_PLAYER_SCREEN: 'SET_PLAYER_SCREEN',
  SUCCESS_LANGUAGE_FETCH: 'SUCCESS_LANGUAGE_FETCH',
}
